[book]
authors = ["johannst"]
language = "en"
multilingual = false
src = "src"
title = "Notes"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/johannst/notes"
git-repository-icon = "fa-github"
